name: Gitflow
on: 
  # To create pull requests.
  push:
    branches: [main,release]
  # To merge pull requests if not possible during the push run. Remove if `auto-merge` is `false`.
  pull_request_review:
  check_run:
    types: [completed]
  release:
    types: [published]
    
jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-latest
    steps:
    - uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        master: main # The `master` branch.