name: Build

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: | 
          npm i
          npm run defs
          npm run build

