name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version-bump.outputs.newTag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: 'Automated Version Bump'
      id: version-bump
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Merge Back to Develop
      uses: Logerfo/gitflow-action@0.0.4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dev: dev # The `dev` branch.
        master: main # The `master` branch.
  BuildRelease:
    runs-on: ubuntu-latest
    needs: CreateRelease
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.CreateRelease.outputs.tag }}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"
        run: | 
          npm i
          npm run defs
          npm run build
          npm run createdist
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.CreateRelease.outputs.tag }}
      - name: Save file in a new orphan storage branch
        uses: StirlingLabs/BranchStorageAction@main
        with:
          src: dist/package
          dst: /
          storage-branch: release