name: Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  CreateRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Automated Version Bump'
      id: version-bump
      uses: 'phips28/gh-action-bump-version@master'
      with:
        tag-prefix: 'v'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge Back to Develop
      uses: Logerfo/gitflow-action@0.0.4
      with:
        dev: dev # The `dev` branch.
        master: main # The `master` branch.
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}